### ISSUE TITLE
MQTT topic for 'warm water setpoint' confusing in English mode

### ISSUE THREAD

**Issue by anarinia** [dewenni/ESP_Buderus_KM271#102]
While in German mode you have a different MQTT topics for warm water setpoint than for warm water actual temperature, in English it is a little confusing:

German:
config/WW_Temperatur    # ww setpoint
status/WW_Isttemperatur # ww actual

English:
config/ww_temp   # ww setpoint
status/ww_temp   # ww actual

(they are actually different topics if you consider the full path, but if one wants to use only the last part as a tag it can cause difficulties)
Is this intentional?

**Comment by dewenni** [comment]
no it is not intentional and I could imagine that we have some more cases where the name of the config value is the same as the status value. I did not pay attention to that and if I change it now, it could break existing implementations.
Therefore I would let it as it is unless there are several people who would like to change this.
