### ISSUE TITLE
Feature request: publish "setvalue" at boot time

### ISSUE THREAD

**Issue by qutschwalze** [dewenni/ESP_Buderus_KM271#11]
Hi, 
it would be nice if all topics are published at boot time so I don't need to create the topics by hand. 
I use iobroker for homeautomation. 

Thanks, 

Jens

**Comment by dewenni** [comment]
Hi @qutschwalze,

I think that this is not the best idea and I don't think that this can solve your Problem here: #10 

1) The behavior of sending messages is the same since the first version. The messages are send after the ESP receives the value from the Logamatic. The ESP is not asking for values to the Logamatic. The ESP is only listening of what the Logamatic sends. At boot-up the software only send the "logging command" to the Logamatic. After that, the Logamatic start to send the values and the Logamatic start to send all config values and then it starts to send the status values.

2) If I would send messages with all configured Topics before the Logamatic send the depending values to that topic, what should be the payload of this initial message? You would receive messages with invalid or unknown values.

3) The principle of MQTT is based on Publish and Subscribe. That is why I don't think that this has something to do with your problem ( #10 ). In your case, ioBroker subscribe to a defined topic at the mitt-broker and not directly at the ESP.
So in my point of view, the ioBroker can not influence the ESP.

If I get you wrong or If I missed something, please let me know.
Otherwise I would close this issue.


Sven
